title: Scopocket Documentation
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

search_enabled: true
auto_page_title: true
version: false

sidebar:
  - getting-started
  - pin-reference
  - manufacturing
  - technical-specs
  - development-history
  - poster